export enum COLORS {
  background = "#111111",
  text = "white",
  border = "white",
  tabIcon = "white",
  tabIconFocused = "#FFBF00",
  tabBackground = "#111111",
  summaryBackground = "#181818",
  summaryText = "white",
  chartLabel = "white",
  chart = "#FFBF00",
  expense = "white",
  income = "white",
  recordBackground = "#181818",
  recordIcon = "white",
  remove = "#FFBF00",
  button = "#FFBF00",
  buttonText = "#111111",
}
