export enum COLORS {
  background = "snow",
  text = "black",
  border = "black",
  tabIcon = "black",
  tabIconFocused = "mediumturquoise",
  tabBackground = "ghostwhite",
  summaryBackground = "snow",
  summaryText = "black",
  chartLabel = "black",
  chart = "mediumturquoise",
  expense = "firebrick",
  income = "royalblue",
  recordBackground = "snow",
  recordIcon = "black",
  archive = "mediumturquoise",
  remove = "firebrick",
  button = "mediumturquoise",
  buttonText = "snow",
}
